[project]
name = "arq-redis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arq>=0.26.3",
    "fastapi[standard]>=0.118.0",
    "httpx>=0.28.1",
    "redis>=5.3.1",
]
